version: 2.1

jobs:
  print:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: print hello
          command: 
            echo 'Hello'
workflows:
  hello_workflow:
    jobs:
      - print